apiVersion: v1
kind: Service
metadata:
  name: devops-challenge-python-app-service
  labels:
    app: devops-challenge-python-app-service
spec:
  type: NodePort
  selector:
    {{- include "devops-challenge-python-app-labels" . }}
  ports:
  - port: 80
    targetPort: 8000
    
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "redis-labels" . }}
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379